// SIAPE GAP V3.4.18 · Área Laboratorio reconstruida desde cero.
// Fuentes de diseño: guía institucional de Laboratorio aportada por el usuario,
// supermatriz de riesgo de laboratorio y matriz histórica de desvíos 2025 (N=46).
// La frecuencia histórica es informativa y NO modifica por sí sola el IIRS de la auditoría actual.

function makeLabItem(code, domain, item, score, opts={}){
  const labels={5:'CRÍTICA',4:'ALTA',3:'MODERADA',2:'BAJA',1:'BAJA',0:'PENDIENTE'};
  return {
    code,
    service:'Laboratorio',
    domain,
    item,
    score,
    riskType:opts.riskType||'CALIDAD / SEGURIDAD DEL PACIENTE',
    impact:opts.impact||'Puede afectar la confiabilidad del proceso de laboratorio, la trazabilidad o la seguridad del paciente.',
    evidence:opts.evidence||'Registros, procedimientos, documentación respaldatoria, entrevistas y verificación directa en terreno.',
    levels:opts.levels||'I, II, III, IV',
    criticality:opts.criticality||labels[score]||'PENDIENTE',
    priority:score>=5?'INMEDIATA':score===4?'ALTA':score===3?'MEDIA':'NORMAL',
    deadline:score>=5?'Inmediato / hasta 24 h':score===4?'Hasta 15 días':score===3?'Hasta 30 días':'Hasta 60 días',
    responsible:opts.responsible||'Dirección Técnica / Responsable del Laboratorio / Calidad',
    theme:opts.theme||domain,
    mira:opts.mira||'Cumplimiento del requisito y su impacto sobre el proceso de laboratorio.',
    normBase:opts.normBase||'BASE DE TRABAJO APORTADA - VALIDAR NORMA APLICABLE',
    process:opts.process||'APOYO',
    subprocess:opts.subprocess||domain,
    sourceRef:opts.sourceRef||'Guía Laboratorio',
    matrixRef:opts.matrixRef||'',
    historicalCount:opts.historicalCount??null,
    historicalFrequency:opts.historicalFrequency??null,
    processCriticality:opts.processCriticality||'',
    patientCriticality:opts.patientCriticality||'',
    contextNote:opts.contextNote||''
  };
}

const LAB_ITEMS=[
  // ESTRUCTURA Y EQUIPAMIENTO - Guía institucional
  makeLabItem('LAB-001','Estructura y equipamiento','El sector de administración es independiente del área de procesamiento de muestras.',3,{process:'APOYO',subprocess:'Infraestructura',sourceRef:'5.1.1.1'}),
  makeLabItem('LAB-002','Estructura y equipamiento','El sector destinado a la toma de muestras se encuentra acondicionado y separado de forma adecuada.',4,{process:'PREANALÍTICO',subprocess:'Extracción',sourceRef:'5.1.1.2',historicalCount:1,historicalFrequency:2.2,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-003','Estructura y equipamiento','El espacio de trabajo del laboratorio es funcional de acuerdo con el equipamiento y el personal.',3,{process:'APOYO',subprocess:'Infraestructura',sourceRef:'5.1.1.4.1'}),
  makeLabItem('LAB-004','Estructura y equipamiento','Cuenta con equipamiento necesario y suficiente para resolver las prácticas que brinda.',5,{process:'ANALÍTICO',subprocess:'Equipamiento',sourceRef:'5.1.1.4.2.1',matrixRef:'Equipamiento suficiente',historicalCount:2,historicalFrequency:4.3,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-005','Estructura y equipamiento','Cuenta con equipo para determinación de gases en sangre cuando el nivel o la existencia de UTI lo requiere.',5,{process:'ANALÍTICO',subprocess:'Capacidad resolutiva',sourceRef:'5.1.1.4.2.2',matrixRef:'Equipo gases',historicalCount:6,historicalFrequency:13.0,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA',contextNote:'Aplicar cuando la complejidad o la existencia de UTI exige esta prestación.'}),
  makeLabItem('LAB-006','Estructura y equipamiento','Dispone de heladera/s y freezer/s de uso exclusivo para el laboratorio y para el material correspondiente.',4,{process:'ANALÍTICO',subprocess:'Conservación',sourceRef:'5.1.1.4.3',matrixRef:'Heladeras exclusivas'}),
  makeLabItem('LAB-007','Estructura y equipamiento','Se realiza y registra el control de temperatura de heladera/s.',4,{process:'ANALÍTICO',subprocess:'Conservación',sourceRef:'5.1.1.4.4.1',matrixRef:'Control temperatura / Registro temperaturas',historicalCount:20,historicalFrequency:43.5,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-008','Estructura y equipamiento','Se realiza y registra el control de temperatura de freezer/s.',4,{process:'ANALÍTICO',subprocess:'Conservación',sourceRef:'5.1.1.4.4.2',matrixRef:'Control temperatura / Registro temperaturas',historicalCount:20,historicalFrequency:43.5,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-009','Estructura y equipamiento','Se realiza y registra el control de temperatura de estufa/s.',4,{process:'ANALÍTICO',subprocess:'Conservación',sourceRef:'5.1.1.4.4.3',matrixRef:'Control temperatura / Registro temperaturas',historicalCount:20,historicalFrequency:43.5,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-010','Estructura y equipamiento','Se realiza y registra el control de temperatura de baño/s termostático/s.',4,{process:'ANALÍTICO',subprocess:'Conservación',sourceRef:'5.1.1.4.4.4',matrixRef:'Control temperatura / Registro temperaturas',historicalCount:20,historicalFrequency:43.5,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-011','Estructura y equipamiento','Los equipos críticos y heladeras se encuentran conectados al grupo electrógeno o a una fuente de respaldo adecuada.',4,{process:'APOYO',subprocess:'Continuidad',sourceRef:'5.1.1.4.5',matrixRef:'Grupo electrógeno'}),
  makeLabItem('LAB-012','Estructura y equipamiento','El sector de lavado se encuentra correctamente separado del área de trabajo.',4,{process:'APOYO',subprocess:'Infraestructura / Bioseguridad',sourceRef:'5.1.1.4.6',matrixRef:'Sector lavado separado',historicalCount:7,historicalFrequency:15.2,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-013','Estructura y equipamiento','El laboratorio dispone de matafuego/extintor accesible y con carga vigente.',4,{process:'APOYO',subprocess:'Seguridad',sourceRef:'5.1.1.4.7',matrixRef:'Matafuego vigente',historicalCount:8,historicalFrequency:17.4,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-014','Estructura y equipamiento','Paredes, revestimientos, mesadas y pisos son impermeables, lavables y adecuados para el trabajo de laboratorio.',3,{process:'APOYO',subprocess:'Infraestructura / Bioseguridad',sourceRef:'5.1.1.4.8',matrixRef:'Superficies lavables',historicalCount:8,historicalFrequency:17.4,processCriticality:'MODERADA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-015','Bacteriología','Bacteriología dispone de un local exclusivo y adecuadamente aislado.',5,{process:'ANALÍTICO',subprocess:'Microbiología',sourceRef:'5.1.1.5.1',matrixRef:'Área exclusiva bacterio',historicalCount:12,historicalFrequency:26.1,processCriticality:'CRÍTICA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-016','Bacteriología','El sector de bacteriología se encuentra correctamente señalizado.',3,{process:'ANALÍTICO',subprocess:'Microbiología',sourceRef:'5.1.1.5.1.1-a'}),
  makeLabItem('LAB-017','Bacteriología','Bacteriología cuenta con ventilación y flujo de aire adecuados al riesgo y a las prácticas realizadas.',5,{process:'ANALÍTICO',subprocess:'Microbiología / Bioseguridad',sourceRef:'5.1.1.5.1.1-b',matrixRef:'Flujo aire',historicalCount:12,historicalFrequency:26.1,processCriticality:'CRÍTICA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-018','Bacteriología','Bacteriología cuenta con estufa adecuada y operativa cuando corresponde.',3,{process:'ANALÍTICO',subprocess:'Microbiología',sourceRef:'5.1.1.5.1.2',matrixRef:'Estufa'}),
  makeLabItem('LAB-019','Bacteriología','Bacteriología cuenta con autoclave o circuito seguro de esterilización/descontaminación del material, según las prácticas realizadas.',4,{process:'ANALÍTICO',subprocess:'Microbiología / Bioseguridad',sourceRef:'5.1.1.5.1.3',matrixRef:'Autoclave',historicalCount:1,historicalFrequency:2.2,processCriticality:'ALTA',patientCriticality:'MODERADA'}),

  // RECURSOS HUMANOS
  makeLabItem('LAB-020','Recursos Humanos','El laboratorio cuenta con Dirección Técnica formalmente identificada.',5,{process:'APOYO',subprocess:'RRHH / Responsabilidad profesional',sourceRef:'5.1.2.1',matrixRef:'Director técnico',historicalCount:7,historicalFrequency:15.2,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-021','Recursos Humanos','El legajo de la Dirección Técnica acredita matrícula vigente.',4,{process:'APOYO',subprocess:'RRHH / Gestión',sourceRef:'5.1.2.2.1',matrixRef:'Matrícula vigente',historicalCount:3,historicalFrequency:6.5,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-022','Recursos Humanos','El legajo de la Dirección Técnica acredita el título correspondiente.',4,{process:'APOYO',subprocess:'RRHH / Gestión',sourceRef:'5.1.2.2.2',historicalCount:3,historicalFrequency:6.5,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-023','Recursos Humanos','Los legajos de los/las bioquímicos/as acreditan matrícula vigente.',4,{process:'APOYO',subprocess:'RRHH / Gestión',sourceRef:'5.1.2.3.1',matrixRef:'Matrícula vigente',historicalCount:3,historicalFrequency:6.5,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-024','Recursos Humanos','Los legajos de los/las bioquímicos/as acreditan el título correspondiente.',4,{process:'APOYO',subprocess:'RRHH / Gestión',sourceRef:'5.1.2.3.2'}),
  makeLabItem('LAB-025','Recursos Humanos','Los legajos del personal técnico de laboratorio acreditan matrícula vigente cuando corresponde.',4,{process:'APOYO',subprocess:'RRHH / Gestión',sourceRef:'5.1.2.4.1',matrixRef:'Personal técnico matriculado'}),
  makeLabItem('LAB-026','Recursos Humanos','Los legajos del personal técnico de laboratorio acreditan el título correspondiente.',4,{process:'APOYO',subprocess:'RRHH / Gestión',sourceRef:'5.1.2.4.2'}),
  makeLabItem('LAB-027','Recursos Humanos','El servicio dispone del personal de limpieza necesario y con asignación adecuada al sector.',3,{process:'APOYO',subprocess:'RRHH / Bioseguridad',sourceRef:'5.1.2.6'}),

  // FUNCIONALIDAD Y CAPACIDAD RESOLUTIVA
  makeLabItem('LAB-028','Funcionalidad','Cuenta con guardia activa las 24 horas cuando el nivel de resolución exige cobertura activa.',5,{process:'APOYO',subprocess:'RRHH / Continuidad',sourceRef:'5.1.3.1',matrixRef:'Guardia activa 24 hs',levels:'III, IV',historicalCount:14,historicalFrequency:30.4,processCriticality:'CRÍTICA*',patientCriticality:'CRÍTICA*',contextNote:'La criticidad depende del nivel de resolución y de la necesidad de respuesta oportuna.'}),
  makeLabItem('LAB-029','Funcionalidad','Hay bioquímico/a presente durante el horario de funcionamiento requerido por el servicio.',5,{process:'APOYO',subprocess:'RRHH / Supervisión',sourceRef:'5.1.3.2',matrixRef:'Supervisión bioquímica',historicalCount:7,historicalFrequency:15.2,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-030','Preanalítica','Se utilizan al menos dos datos para la identificación inequívoca de las muestras.',5,{process:'PREANALÍTICO',subprocess:'Identificación / Trazabilidad',sourceRef:'5.1.3.3',matrixRef:'Identificación ≥2 datos',historicalCount:13,historicalFrequency:28.3,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-031','Prácticas','Se realizan determinaciones de coagulación básica (TP/KPTT) cuando corresponden al nivel y cartera prestacional.',4,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.1',matrixRef:'Coagulación TP/KPTT'}),
  makeLabItem('LAB-032','Prácticas','Se realizan determinaciones de plaquetas cuando corresponden al nivel y cartera prestacional.',4,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.2',matrixRef:'Plaquetas'}),
  makeLabItem('LAB-033','Prácticas','Se realiza hemograma cuando corresponde al nivel y cartera prestacional.',5,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.3',matrixRef:'Hemograma'}),
  makeLabItem('LAB-034','Prácticas','Se realiza química básica (ionograma, glucemia, uremia y creatinina) cuando corresponde.',4,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.4',matrixRef:'Química básica'}),
  makeLabItem('LAB-035','Prácticas','Se realiza calcemia cuando corresponde al nivel y cartera prestacional.',3,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.5',matrixRef:'Calcemia'}),
  makeLabItem('LAB-036','Prácticas','Se realizan AST, ALT y FAL cuando corresponde al nivel y cartera prestacional.',3,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.6',matrixRef:'AST/ALT/FAL'}),
  makeLabItem('LAB-037','Prácticas','Se realiza amilasa cuando corresponde al nivel y cartera prestacional.',2,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.7',matrixRef:'Amilasa'}),
  makeLabItem('LAB-038','Prácticas','Se realizan enzimas cardíacas (CK/CK-MB/Troponina) cuando corresponde a la capacidad resolutiva requerida.',5,{process:'ANALÍTICO',subprocess:'Urgencias / Prácticas',sourceRef:'5.1.3.4.8',matrixRef:'Enzimas cardíacas'}),
  makeLabItem('LAB-039','Prácticas','Se realiza orina completa cuando corresponde al nivel y cartera prestacional.',3,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.9',matrixRef:'Orina completa'}),
  makeLabItem('LAB-040','Prácticas','Se realizan estudios físico-químicos y recuento celular de líquidos de punción cuando corresponde.',4,{process:'ANALÍTICO',subprocess:'Prácticas',sourceRef:'5.1.3.4.10',matrixRef:'Líquidos punción'}),
  makeLabItem('LAB-041','Reactivos y controles','Los reactivos utilizados se encuentran dentro de su período de vigencia.',5,{process:'ANALÍTICO',subprocess:'Reactivos',sourceRef:'5.1.3.5',historicalCount:11,historicalFrequency:23.9,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),

  // CONTROL DE CALIDAD INTERNO
  makeLabItem('LAB-042','Control de calidad interno','Se realiza control de calidad interno de las determinaciones analíticas.',5,{process:'ANALÍTICO',subprocess:'Control interno',sourceRef:'5.1.3.6',matrixRef:'QC Química / Hematología / Hemostasia / ácido-base',historicalCount:22,historicalFrequency:47.8,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-043','Control de calidad interno','El control de calidad interno se realiza con frecuencia diaria o con la frecuencia técnicamente establecida.',5,{process:'ANALÍTICO',subprocess:'Control interno',sourceRef:'5.1.3.6.1',historicalCount:22,historicalFrequency:47.8,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-044','Control de calidad interno','El control interno se aplica a todos los equipos y prácticas que requieren control.',5,{process:'ANALÍTICO',subprocess:'Control interno',sourceRef:'5.1.3.6.2',historicalCount:22,historicalFrequency:47.8,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-045','Control de calidad interno','Los resultados del control de calidad interno quedan registrados y son trazables.',5,{process:'ANALÍTICO',subprocess:'Control interno',sourceRef:'5.1.3.6.3',historicalCount:22,historicalFrequency:47.8,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-046','Control de calidad interno','Los controles internos reciben tratamiento estadístico y análisis de tendencias.',4,{process:'ANALÍTICO',subprocess:'Gestión de calidad',sourceRef:'5.1.3.6.4',matrixRef:'Levey Jennings'}),
  makeLabItem('LAB-047','Control de calidad interno','Se registran e implementan acciones correctivas ante resultados de control interno fuera de aceptación.',5,{process:'ANALÍTICO',subprocess:'Gestión de calidad',sourceRef:'5.1.3.6.5',matrixRef:'Acciones correctivas'}),

  // CONTROL DE CALIDAD EXTERNO
  makeLabItem('LAB-048','Control de calidad externo','El laboratorio participa en un programa de evaluación externa de la calidad (PEEC o equivalente) cuando corresponde.',4,{process:'ANALÍTICO',subprocess:'Aseguramiento de calidad',sourceRef:'5.1.3.7',matrixRef:'PEEC',historicalCount:15,historicalFrequency:32.6,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-049','Control de calidad externo','El control de calidad externo se realiza con la frecuencia establecida por el proveedor/programa.',4,{process:'ANALÍTICO',subprocess:'Aseguramiento de calidad',sourceRef:'5.1.3.7.1',historicalCount:15,historicalFrequency:32.6,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-050','Control de calidad externo','La evaluación externa abarca los equipos y prácticas que deben estar incluidos.',4,{process:'ANALÍTICO',subprocess:'Aseguramiento de calidad',sourceRef:'5.1.3.7.2',historicalCount:15,historicalFrequency:32.6,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-051','Control de calidad externo','Los resultados de evaluación externa quedan registrados.',4,{process:'ANALÍTICO',subprocess:'Aseguramiento de calidad',sourceRef:'5.1.3.7.3'}),
  makeLabItem('LAB-052','Control de calidad externo','Los reportes de evaluación externa se encuentran disponibles para su visualización y auditoría.',4,{process:'ANALÍTICO',subprocess:'Aseguramiento de calidad',sourceRef:'5.1.3.7.4'}),
  makeLabItem('LAB-053','Control de calidad externo','Se registran acciones correctivas ante resultados no conformes de la evaluación externa.',4,{process:'ANALÍTICO',subprocess:'Aseguramiento de calidad',sourceRef:'5.1.3.7.5'}),

  // MANTENIMIENTO, TRAZABILIDAD Y POSTANALÍTICA
  makeLabItem('LAB-054','Equipamiento y mantenimiento','Existe registro actualizado del mantenimiento preventivo efectuado a los equipos.',4,{process:'ANALÍTICO',subprocess:'Equipamiento',sourceRef:'5.1.3.8',historicalCount:4,historicalFrequency:8.7,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-055','Equipamiento y mantenimiento','Existe registro actualizado del mantenimiento correctivo efectuado a los equipos.',4,{process:'ANALÍTICO',subprocess:'Equipamiento',sourceRef:'5.1.3.9',historicalCount:4,historicalFrequency:8.7,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-056','Trazabilidad y postanalítica','Existe registro trazable de las derivaciones de muestras y estudios.',4,{process:'POSTANALÍTICO',subprocess:'Derivaciones / Trazabilidad',sourceRef:'5.1.3.10',matrixRef:'Registro derivaciones'}),
  makeLabItem('LAB-057','Trazabilidad y postanalítica','El informe de laboratorio contiene identificación del paciente, determinación, laboratorio que efectuó el análisis, tipo de muestra, fecha de toma e identificación del profesional que valida el resultado.',5,{process:'POSTANALÍTICO',subprocess:'Informe / Validación',sourceRef:'5.1.3.11',matrixRef:'Informe completo / Validación bioquímica',historicalCount:3,historicalFrequency:6.5,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-058','Trazabilidad y postanalítica','Existe respaldo o back up de los resultados, sea manual o informático.',4,{process:'POSTANALÍTICO',subprocess:'Información / Resguardo',sourceRef:'5.1.3.12',matrixRef:'Resguardo informes'}),
  makeLabItem('LAB-059','Gestión de calidad','Existe Manual de Procedimientos actualizado, accesible y aplicable a las prácticas realizadas.',4,{process:'APOYO',subprocess:'Gestión de calidad',sourceRef:'5.1.3.13',historicalCount:20,historicalFrequency:43.5,processCriticality:'ALTA',patientCriticality:'MODERADA'}),

  // BIOSEGURIDAD
  makeLabItem('LAB-060','Bioseguridad','Existe Manual de Bioseguridad de fácil acceso y conocido por todo el personal.',4,{process:'APOYO',subprocess:'Gestión de calidad / Bioseguridad',sourceRef:'5.1.4.1',historicalCount:20,historicalFrequency:43.5,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-061','Bioseguridad','Existen procedimientos escritos para limpieza de superficies y lavado de material.',4,{process:'APOYO',subprocess:'Bioseguridad',sourceRef:'5.1.4.2'}),
  makeLabItem('LAB-062','Bioseguridad','Existen procedimientos escritos para el manejo de residuos patogénicos y/o peligrosos.',4,{process:'APOYO',subprocess:'Residuos',sourceRef:'5.1.4.3',historicalCount:7,historicalFrequency:15.2,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-063','Bioseguridad','Se realiza tratamiento y/o descarte seguro de líquidos residuales químicos o biológicos provenientes de equipos.',4,{process:'APOYO',subprocess:'Residuos / Bioseguridad',sourceRef:'5.1.4.4',historicalCount:12,historicalFrequency:26.1,processCriticality:'ALTA',patientCriticality:'BAJA'}),
  makeLabItem('LAB-064','Bioseguridad','Se realiza una gestión segura de residuos provenientes de bacteriología, biología molecular y virología.',4,{process:'APOYO',subprocess:'Residuos / Bioseguridad',sourceRef:'5.1.4.5'}),
  makeLabItem('LAB-065','Bioseguridad','El personal dispone y utiliza elementos de barrera descartables adecuados (guantes, camisolín, antiparras y barbijo) según el riesgo de la tarea.',4,{process:'APOYO',subprocess:'EPP',sourceRef:'5.1.4.6'}),
  makeLabItem('LAB-066','Preanalítica','Cuando se utilizan tubos de preparación institucional o material no industrial, existen instructivos escritos de preparación, lavado, identificación y control que evitan reutilizaciones o anticoagulantes inadecuados.',5,{process:'PREANALÍTICO',subprocess:'Tubos / Integridad de muestra',sourceRef:'5.1.2.3.1',historicalCount:11,historicalFrequency:23.9,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-067','Bioseguridad','Existe bolsa roja disponible y utilizada correctamente para residuos patogénicos.',4,{process:'APOYO',subprocess:'Residuos',sourceRef:'5.1.2.4.1',historicalCount:7,historicalFrequency:15.2,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-068','Bioseguridad','Existen descartadores rígidos y adecuados para elementos cortopunzantes en los puntos de generación.',5,{process:'APOYO',subprocess:'Residuos / Cortopunzantes',sourceRef:'5.1.2.4.2',historicalCount:1,historicalFrequency:2.2,processCriticality:'CRÍTICA',patientCriticality:'MODERADA'}),

  // COMPLEMENTOS DE LA SUPERMATRIZ Y DE LOS DESVÍOS HISTÓRICOS
  makeLabItem('LAB-069','Preanalítica','Existe concordancia verificable entre paciente, solicitud y muestra durante todo el proceso preanalítico.',5,{process:'PREANALÍTICO',subprocess:'Identificación / Trazabilidad',sourceRef:'Supermatriz',matrixRef:'Concordancia paciente-muestra'}),
  makeLabItem('LAB-070','Preanalítica','Se utilizan tubos, recipientes y anticoagulantes correctos para cada determinación y tipo de muestra.',5,{process:'PREANALÍTICO',subprocess:'Preparación / Integridad de muestra',sourceRef:'Supermatriz',matrixRef:'Tipo correcto tubos',historicalCount:11,historicalFrequency:23.9,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-071','Preanalítica','Se registra el ingreso y recepción de las muestras con trazabilidad suficiente.',4,{process:'PREANALÍTICO',subprocess:'Recepción / Trazabilidad',sourceRef:'Supermatriz',matrixRef:'Registro ingreso muestras'}),
  makeLabItem('LAB-072','Preanalítica','Se controlan y registran los tiempos relevantes entre toma, recepción y procesamiento de muestras.',4,{process:'PREANALÍTICO',subprocess:'Recepción / Oportunidad',sourceRef:'Supermatriz',matrixRef:'Tiempos recepción'}),
  makeLabItem('LAB-073','Preanalítica','El área de extracción dispone de condiciones e insumos para higiene de manos y prácticas seguras.',4,{process:'PREANALÍTICO',subprocess:'Extracción / Bioseguridad',sourceRef:'Supermatriz',matrixRef:'Lavado manos'}),
  makeLabItem('LAB-074','Reactivos y controles','Se mantiene trazabilidad de reactivos y controles, incluyendo lote, vencimiento y preparación cuando corresponde.',4,{process:'ANALÍTICO',subprocess:'Reactivos / Calidad',sourceRef:'Supermatriz + histórico 2025',historicalCount:9,historicalFrequency:19.6,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-075','Trazabilidad y postanalítica','Los resultados son revisados y validados por profesional bioquímico/a conforme a la organización del servicio.',5,{process:'POSTANALÍTICO',subprocess:'Validación',sourceRef:'Supermatriz + histórico 2025',matrixRef:'Validación bioquímica',historicalCount:3,historicalFrequency:6.5,processCriticality:'CRÍTICA',patientCriticality:'CRÍTICA'}),
  makeLabItem('LAB-076','Trazabilidad y postanalítica','Los informes incluyen valores o intervalos de referencia cuando corresponden.',3,{process:'POSTANALÍTICO',subprocess:'Informe',sourceRef:'Supermatriz',matrixRef:'Valores referencia'}),
  makeLabItem('LAB-077','Trazabilidad y postanalítica','Existe un procedimiento documentado para comunicación oportuna de valores críticos y su registro.',5,{process:'POSTANALÍTICO',subprocess:'Seguridad del paciente / Comunicación',sourceRef:'Supermatriz',matrixRef:'Valores críticos'}),
  makeLabItem('LAB-078','Trazabilidad y postanalítica','El sistema de registro de solicitudes, resultados y trazabilidad (manual o LIS) es suficiente, seguro y recuperable.',4,{process:'POSTANALÍTICO',subprocess:'Informática / Información',sourceRef:'Supermatriz',matrixRef:'Sistema LIS',historicalCount:4,historicalFrequency:8.7,processCriticality:'MODERADA',patientCriticality:'BAJA'}),
  makeLabItem('LAB-079','Trazabilidad y postanalítica','Los informes y resultados se archivan y resguardan de forma trazable durante el período institucional definido.',3,{process:'POSTANALÍTICO',subprocess:'Documentación / Archivo',sourceRef:'Supermatriz',matrixRef:'Resguardo informes'}),
  makeLabItem('LAB-080','Gestión de calidad','El laboratorio utiliza indicadores de calidad para monitorear sus procesos y definir acciones de mejora.',3,{process:'APOYO',subprocess:'Gestión de calidad',sourceRef:'Supermatriz',matrixRef:'Indicadores calidad'}),
  makeLabItem('LAB-081','Recursos Humanos','Existe un programa de capacitación y actualización del personal de laboratorio con registros de participación.',3,{process:'APOYO',subprocess:'RRHH / Capacitación',sourceRef:'Supermatriz',matrixRef:'Capacitación personal'}),
  makeLabItem('LAB-082','Tercerización','Cuando el laboratorio es tercerizado, existe convenio o contrato vigente que define alcance, responsabilidades y prestaciones.',4,{process:'APOYO',subprocess:'Gestión / Tercerización',sourceRef:'Histórico 2025',historicalCount:2,historicalFrequency:4.3,processCriticality:'ALTA',patientCriticality:'BAJA',contextNote:'Marcar NO APLICA cuando el servicio no es tercerizado.'}),
  makeLabItem('LAB-083','Tercerización','Cuando existe tercerización, el prestador permite auditar o verificar el laboratorio contratado y su cumplimiento.',4,{process:'APOYO',subprocess:'Gestión / Tercerización',sourceRef:'Histórico 2025',historicalCount:4,historicalFrequency:8.7,processCriticality:'ALTA',patientCriticality:'MODERADA',contextNote:'Marcar NO APLICA cuando el servicio no es tercerizado.'}),
  makeLabItem('LAB-084','Trazabilidad y postanalítica','Las solicitudes y resultados se comunican por canales institucionales seguros, trazables y adecuados, evitando medios no formalizados para información sensible.',4,{process:'POSTANALÍTICO',subprocess:'Información / Comunicación',sourceRef:'Histórico 2025',historicalCount:3,historicalFrequency:6.5,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-085','Bioseguridad','No se almacenan alimentos, bebidas ni objetos domésticos en áreas técnicas o heladeras destinadas al laboratorio.',4,{process:'APOYO',subprocess:'Bioseguridad / Almacenamiento',sourceRef:'Histórico 2025',historicalCount:4,historicalFrequency:8.7,processCriticality:'ALTA',patientCriticality:'MODERADA'}),
  makeLabItem('LAB-086','Estructura y equipamiento','Los insumos, cajas y materiales se almacenan ordenados y separados del piso, sin obstaculizar circulación ni limpieza.',3,{process:'APOYO',subprocess:'Almacenamiento / Infraestructura',sourceRef:'Histórico 2025',historicalCount:6,historicalFrequency:13.0,processCriticality:'MODERADA',patientCriticality:'BAJA'}),
  makeLabItem('LAB-087','Estructura y equipamiento','Las fuentes inflamables, garrafas, mecheros o calefones se encuentran gestionados de forma segura y compatible con el riesgo del laboratorio.',5,{process:'APOYO',subprocess:'Seguridad / Infraestructura',sourceRef:'Histórico 2025',historicalCount:6,historicalFrequency:13.0,processCriticality:'CRÍTICA',patientCriticality:'ALTA',contextNote:'La criticidad depende del tipo de fuente y del riesgo concreto observado.'}),
  makeLabItem('LAB-088','Bacteriología','El cerramiento y la segregación del sector de bacteriología se mantienen durante las actividades que lo requieren.',4,{process:'ANALÍTICO',subprocess:'Microbiología / Bioseguridad',sourceRef:'Histórico 2025',historicalCount:6,historicalFrequency:13.0,processCriticality:'ALTA',patientCriticality:'ALTA'}),
  makeLabItem('LAB-089','Estructura y equipamiento','Las aberturas del laboratorio cuentan con barreras o medidas adecuadas para evitar ingreso de vectores cuando corresponde.',3,{process:'APOYO',subprocess:'Infraestructura',sourceRef:'Histórico 2025',historicalCount:7,historicalFrequency:15.2,processCriticality:'MODERADA',patientCriticality:'BAJA'})
];

const LAB_NORMS=[
  {id:'LAB-N01',scope:'Referencia técnica',jurisdiction:'General',type:'Sistema de gestión de calidad',number:'ISO 15189',regulation:'Referencia incorporada en la Supermatriz aportada',authority:'Norma técnica',service:'Laboratorio',status:'REFERENCIA DE MATRIZ - VALIDAR EDICIÓN, ALCANCE Y APLICABILIDAD',notes:'Utilizada como referencia de trabajo en trazabilidad, calidad y competencia del laboratorio.'},
  {id:'LAB-N02',scope:'Referencia técnica',jurisdiction:'General',type:'Sistema de gestión',number:'ISO 9001',regulation:'Referencia incorporada en la Supermatriz aportada',authority:'Norma técnica',service:'Laboratorio',status:'REFERENCIA DE MATRIZ - VALIDAR APLICABILIDAD',notes:'Referencia de trabajo para gestión de calidad y acciones correctivas.'},
  {id:'LAB-N03',scope:'Referencia prestacional',jurisdiction:'Nación',type:'Programa / cartera de prestaciones',number:'PMO',regulation:'Referencia incorporada en la Supermatriz aportada',authority:'Autoridad sanitaria nacional',service:'Laboratorio',status:'BASE DE TRABAJO - VALIDAR TEXTO VIGENTE Y ALCANCE',notes:'Utilizada en la matriz para prácticas básicas.'},
  {id:'LAB-N04',scope:'Referencia de calidad',jurisdiction:'General',type:'Evaluación externa de calidad',number:'PEEC / programa equivalente',regulation:'Según proveedor o programa aplicable',authority:'Programa de evaluación externa',service:'Laboratorio',status:'VALIDAR PROGRAMA APLICABLE',notes:'La participación y frecuencia deben evaluarse según prácticas y programa contratado.'},
  {id:'LAB-N05',scope:'Documento institucional',jurisdiction:'INSSJP / GAP',type:'Guía de auditoría',number:'Auditoría Integral - Laboratorio',regulation:'Guía de Laboratorio aportada para SIAPE',authority:'Gerencia de Auditoría Prestacional',service:'Laboratorio',status:'DOCUMENTO BASE APORTADO',notes:'Base estructural de requisitos y datos del servicio para esta versión.'}
];

ITEMS.push(...LAB_ITEMS);
NORMS.push(...LAB_NORMS);
